### PR TITLE
RES-83 Add nab to nupic regression tests (v. 6)

### PR DESCRIPTION
**Pull request by SaganBolliger**
https://jira.numenta.com/browse/RES-83
Sixth PR in series incorporating feedback from #25, #26, #27, #28, and #29.

Tests were timing out when attempting to run NAB from within a regression test. Instead, running NAB from Travis build script, and simply checking output in the regression test.

@rhyolight Can you check let me know if you think this strategy will work, and if so, merge the changes?

### CODE REVIEW

**Comment by rhyolight** [comment]
@SaganBolliger Where is the test output being checked?

**Comment by SaganBolliger** [comment]
@rhyolight In https://github.com/SaganBolliger/nupic.regression/blob/RES-83-add-NAB-to-nupic-regression-tests/tests/anomaly/nab/nab_anomaly_test.py

Running NAB write the results file results/final_results.json

**Comment by rhyolight** [comment]
Ok let's try it

**Comment by SaganBolliger** [comment]
Looks like this one did the trick.

**Pull request merged**
