### PR TITLE
NUP-2384 Adjusted expected results in benchmark_results.json following changes in nupic.core

### PR DESCRIPTION
**Pull request by vitaly-krugl**

### CODE REVIEW

**Comment by scottpurdy** [comment]
@oxtopus - No. We would only change Numenta NAB scores if we wanted to resubmit a different version of the algorithm (just like any of the other people that submitted algorithms). The score we show in NAB corresponds to a specific release of nupic.

**Comment by vitaly-krugl** [comment]
Strange - the build https://ci.numenta.com/browse/NUP-REGR-JOB1-258 succeeded, but `continuous-integration/bamboo` still doesn't have a status of any kind in github GUI.

**Comment by vitaly-krugl** [comment]
Strange - the build https://ci.numenta.com/browse/NUP-REGR-JOB1-258 succeeded, but `continuous-integration/bamboo` still doesn't have a status of any kind in github GUI.

cc @oxtopus @scottpurdy

**Comment by oxtopus** [comment]
@vitaly-krugl numenta/nupic.regression is not configured to send status reports to github status api.  I enabled it just now and am running to see if that results in a status change

**Pull request merged**
