### PR TITLE
regression: install requirements.txt

### PR DESCRIPTION
**Pull request by breznak**
Simplify install to use requirements.txt as elsewhere

### CODE REVIEW

**Comment by rhyolight** [comment]
depends on https://github.com/numenta/nupic/issues/2606

**Comment by rhyolight** [comment]
@breznak merge in master please

**Comment by breznak** [comment]
yessir

**Comment by scottpurdy** [comment]
@rhyolight - The Travis build is consistently failing but it doesn't seem related to this change. Do you know what's up?

**Comment by rhyolight** [comment]
@scottpurdy I think it's cause the PR is so old. We are not even running this in Travis anymore. I am replacing this with #65 @breznak

**Comment by scottpurdy** [comment]
Ok thanks @breznak

**Pull request merged**
